services:
  typesense:
    image: typesense/typesense:27.1
    container_name: typesense
    restart: on-failure
    ports:
      - "8108:8108"
    env_file:
      - ./.env
    volumes:
      - ./typesense-data:/data
      - ./schema:/schema # Mount schema directory to container
    command: '--data-dir /data --api-key=hustlesasa --enable-cors'
    networks:
      - hustlesasa
networks:
  hustlesasa: