services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
        - ./neo4j/logs:/logs
        - ./neo4j/config:/config
        - ./neo4j/data:/data
        - ./neo4j/plugins:/plugins
    env_file:
        - ./.env
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    networks:
      - hustlesasa
networks:
  hustlesasa: